# Generated by Django 3.0.6 on 2020-10-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200704_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='isnonveg',
            field=models.BooleanField(default=False),
        ),
    ]
