# Generated by Django 3.0.6 on 2020-10-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201019_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
