# Generated by Django 3.0.6 on 2020-10-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201020_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='charge',
            new_name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
