# Generated by Django 3.0.6 on 2020-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201201_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Processed', 'Processed'), ('Pickup', 'Pickup'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
