main:
    debug: True

log:
    backupCount: 100
    maxBytes: 10485760
    log-path: log/
    file-name: cpanel.log

database:
    name: adminpanel
    username: root
    password: 
    host: localhost
    port: 3306


